apiVersion: apps/v1
kind: Deployment
metadata:
  name: empty-test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: empty 
        image: empty:1.0.0
        imagePullPolicy: Never

